// <auto-generated />
using System;
using FisioMetric.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FisioMetric.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20240225022706_Update1-24-02-24")]
    partial class Update1240224
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("FisioMetric.Models.Entidades.Avaliacao", b =>
                {
                    b.Property<int>("RelatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntecedenteCardiopatia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntecedenteDiabete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntecedenteHereditario")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntecedenteHipertensao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntecedenteNeoplasias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabecaCervical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coluna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagClinico")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagFisioterapeutico")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DoencaCardiaca")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaCovid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaDermatologica")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaEndocrina")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaGastroIntestinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaMetabolica")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaNeurologicas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaRespiratorias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaVasculares")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoencaVisual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Equilibrio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstabilidadeEscapular")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Etilismo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExameFisico")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FroxidaoLigamentar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HabitosAlimentacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Joelhos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medicacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MobilidadeColuna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjetivoPessoal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetivoTerapeutico")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsAntecedente")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsMedicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoDoenca")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ombros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PadraoMovimento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pelve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tabagismo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TratamentoAnterior")
                        .HasColumnType("TEXT");

                    b.HasKey("RelatorioId");

                    b.ToTable("avaliacoes", (string)null);
                });

            modelBuilder.Entity("FisioMetric.Models.Entidades.Evolucao", b =>
                {
                    b.Property<int>("IdEvolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anotacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aparelho")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteChegou")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteSaiu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtividade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fisioterapeuta")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEvolucao");

                    b.ToTable("evolucoes", (string)null);
                });

            modelBuilder.Entity("FisioMetric.Models.Entidades.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUltimaAtividade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUltimaAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("pacientes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
